services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/dental-smile
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: dental_mongodb  
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: